package quanlythuvien.model;

import java.sql.Date;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thanhvien generated by hbm2java
 */
@Entity
@Table(name = "thanhvien", catalog = "quanlythuvien")
public class ThanhVien implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String idThanhVien;
	private String tenThanhVien;
	private String email;
	private Date ngaySinh;
	private String gioiTinh;
	private String tinhTrang;
	private String ngayThem;
	private String ngayCapNhat;
	private Set<ThongTinMuonTra> listThongTinMuonTra = new HashSet<ThongTinMuonTra>();

	public ThanhVien() {
	}

	public ThanhVien(String idThanhVien, String tenThanhVien, Date ngaySinh, String gioiTinh, String capDo,
			String tinhTrang, String ngayThem) {
		this.idThanhVien = idThanhVien;
		this.tenThanhVien = tenThanhVien;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.tinhTrang = tinhTrang;
		this.ngayThem = ngayThem;
	}

	public ThanhVien(String idThanhVien, String tenThanhVien, String email, Date ngaySinh, String gioiTinh,
			String capDo, String tinhTrang, String ngayThem, String ngayCapNhat,
			Set<ThongTinMuonTra> listThongTinMuonTra) {
		this.idThanhVien = idThanhVien;
		this.tenThanhVien = tenThanhVien;
		this.email = email;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.tinhTrang = tinhTrang;
		this.ngayThem = ngayThem;
		this.ngayCapNhat = ngayCapNhat;
		this.listThongTinMuonTra = listThongTinMuonTra;
	}

	@Id
	@Column(name = "idthanhvien", unique = true, nullable = false, length = 45)
	public String getIdThanhVien() {
		return this.idThanhVien;
	}

	public void setIdThanhVien(String idThanhVien) {
		this.idThanhVien = idThanhVien;
	}

	@Column(name = "tenthanhvien", nullable = false, length = 45)
	public String getTenThanhVien() {
		return this.tenThanhVien;
	}

	public void setTenThanhVien(String tenThanhVien) {
		this.tenThanhVien = tenThanhVien;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ngaysinh", nullable = false)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "gioitinh", nullable = false, length = 45)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "tinhtrang", nullable = false, length = 45)
	public String getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@Column(name = "ngaythem", nullable = false, length = 45)
	public String getNgayThem() {
		return this.ngayThem;
	}

	public void setNgayThem(String ngayThem) {
		this.ngayThem = ngayThem;
	}

	@Column(name = "ngaycapnhat", length = 45)
	public String getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(String ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thanhVien")
	public Set<ThongTinMuonTra> getListThongTinMuonTra() {
		return this.listThongTinMuonTra;
	}

	public void setListThongTinMuonTra(Set<ThongTinMuonTra> listThongTinMuonTra) {
		this.listThongTinMuonTra = listThongTinMuonTra;
	}

	public static Comparator<ThanhVien> compareAscendingName = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getTenThanhVien();
			String dbName2 = db2.getTenThanhVien();
			return dbName1.compareTo(dbName2);
		}
	};
	
	public static Comparator<ThanhVien> compareDecendingName = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getTenThanhVien();
			String dbName2 = db2.getTenThanhVien();
			return dbName2.compareTo(dbName1);
		}
	};
	
	public static Comparator<ThanhVien> compareAscendingGioiTinh = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getGioiTinh();
			String dbName2 = db2.getGioiTinh();
			return dbName1.compareTo(dbName2);
		}
	};
	
	public static Comparator<ThanhVien> compareDecendingGioiTinh = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getGioiTinh();
			String dbName2 = db2.getGioiTinh();
			return dbName2.compareTo(dbName1);
		}
	};
	
	public static Comparator<ThanhVien> compareAscendingTinhTrang = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getTinhTrang();
			String dbName2 = db2.getTinhTrang();
			return dbName1.compareTo(dbName2);
		}
	};
	
	public static Comparator<ThanhVien> compareDecendingTinhTrang = new Comparator<ThanhVien>() {
		public int compare(ThanhVien db1, ThanhVien db2) {
			String dbName1 = db1.getTinhTrang();
			String dbName2 = db2.getTinhTrang();
			return dbName2.compareTo(dbName1);
		}
	};
}
